[package]
name = "reg_rw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
clap-num = "1.1.1"
log = "0.4.21"
memmap2 = "0.9.4"
simple_logger = "5.0.0"
